package repository

import (
	"context"
	"time"

	"geo-entity-manager/backend/internal/domain"

	"github.com/google/uuid"
)

// getJavaSeedEntities returns 46 realistic geospatial entities scattered across Java island.
func getJavaSeedEntities() []*domain.Entity {
	now := time.Now().UTC()

	return []*domain.Entity{
		// ==========================================
		// 1. DKI JAKARTA & JABODETABEK (8 ENTITIES)
		// ==========================================
		{
			ID:          uuid.NewString(),
			Name:        "Pusat Logistik Nasional Tanjung Priok",
			Type:        domain.EntityTypeFacility,
			Status:      domain.EntityStatusActive,
			Description: "Terminal kontainer internasional dan pergudangan berikat utama DKI Jakarta.",
			Attributes: map[string]interface{}{
				"capacity_teus":    15000,
				"dock_cranes":      18,
				"customs_zone":     "Kawasan Berikat Prioritas",
				"facility_manager": "Budi Santoso, S.T.",
				"operating_hours":  "24/7",
			},
			Latitude:  -6.1042,
			Longitude: 106.8833,
			CreatedAt: now.Add(-120 * time.Hour),
			UpdatedAt: now.Add(-15 * time.Minute),
		},
		{
			ID:          uuid.NewString(),
			Name:        "Armada Truk Kontainer Priok Alpha-01",
			Type:        domain.EntityTypeVehicle,
			Status:      domain.EntityStatusActive,
			Description: "Truk tronton kontainer pengangkut suku cadang industri rute Priok - Cikarang Dry Port.",
			Attributes: map[string]interface{}{
				"license_plate":  "B 9102 UY",
				"fuel_level_pct": 78,
				"speed_kmh":      45,
				"driver_name":    "Agus Setiawan",
				"cargo_type":     "Electronics & Auto Parts",
			},
			Latitude:  -6.1150,
			Longitude: 106.8920,
			CreatedAt: now.Add(-48 * time.Hour),
			UpdatedAt: now.Add(-5 * time.Minute),
		},
		{
			ID:          uuid.NewString(),
			Name:        "Sensor Kualitas Udara Bundaran HI",
			Type:        domain.EntityTypeIoTDevice,
			Status:      domain.EntityStatusActive,
			Description: "Stasiun telemetri mikro-klimat mengukur PM2.5, PM10, SO2, CO2, dan kebisingan lalu lintas Sudirman-Thamrin.",
			Attributes: map[string]interface{}{
				"pm25_ugm3":        34.5,
				"aqi_index":        98,
				"temperature_c":    31.2,
				"humidity_pct":     68,
				"firmware_version": "v4.2.1-iot",
			},
			Latitude:  -6.1950,
			Longitude: 106.8230,
			CreatedAt: now.Add(-200 * time.Hour),
			UpdatedAt: now.Add(-2 * time.Minute),
		},
		{
			ID:          uuid.NewString(),
			Name:        "Sensor Ketinggian Air Pintu Air Manggarai",
			Type:        domain.EntityTypeIoTDevice,
			Status:      domain.EntityStatusActive,
			Description: "Telemetri ultrasonik pemantauan debit dan elevasi air pencegahan banjir aliran Sungai Ciliwung.",
			Attributes: map[string]interface{}{
				"water_level_cm": 640,
				"status_siaga":   "Siaga 4 (Normal)",
				"flow_rate_m3s":  85.2,
				"backup_battery": "100% (Solar)",
			},
			Latitude:  -6.2085,
			Longitude: 106.8485,
			CreatedAt: now.Add(-300 * time.Hour),
			UpdatedAt: now.Add(-1 * time.Minute),
		},
		{
			ID:          uuid.NewString(),
			Name:        "Mobil Patroli Keamanan Cyber SCBD",
			Type:        domain.EntityTypeVehicle,
			Status:      domain.EntityStatusActive,
			Description: "Unit patroli infrastruktur jaringan serat optik dan inspeksi keamanan digital kawasan finansial.",
			Attributes: map[string]interface{}{
				"license_plate":  "B 1120 KPB",
				"fuel_level_pct": 92,
				"speed_kmh":      25,
				"equipment":      "Spectrum Analyzer, SatComm, Fiber Splicer",
			},
			Latitude:  -6.2260,
			Longitude: 106.8080,
			CreatedAt: now.Add(-12 * time.Hour),
			UpdatedAt: now.Add(-8 * time.Minute),
		},
		{
			ID:          uuid.NewString(),
			Name:        "Stasiun Cuaca Pulau Pramuka",
			Type:        domain.EntityTypeIoTDevice,
			Status:      domain.EntityStatusActive,
			Description: "Radar anemometer dan tinggi gelombang maritim Kepulauan Seribu.",
			Attributes: map[string]interface{}{
				"wind_speed_knots": 14.2,
				"wave_height_m":    0.8,
				"battery_pct":      96,
				"solar_charging":   true,
			},
			Latitude:  -5.7450,
			Longitude: 106.6150,
			CreatedAt: now.Add(-150 * time.Hour),
			UpdatedAt: now.Add(-10 * time.Minute),
		},
		{
			ID:          uuid.NewString(),
			Name:        "Pusat Data Nasional Cikarang-Jakarta",
			Type:        domain.EntityTypeFacility,
			Status:      domain.EntityStatusActive,
			Description: "Tier 4 Hyperscale Data Center & Interconnect Gateway kawasan Jabodetabek.",
			Attributes: map[string]interface{}{
				"rack_capacity":    2500,
				"pue_rating":       1.28,
				"security_tier":    "Tier IV Uptime Institute",
				"cooling_system":   "Closed-loop Liquid Immersion",
				"facility_manager": "Dr. Ir. Denny Pratama",
			},
			Latitude:  -6.2415,
			Longitude: 106.9925,
			CreatedAt: now.Add(-500 * time.Hour),
			UpdatedAt: now.Add(-1 * time.Hour),
		},
		{
			ID:          uuid.NewString(),
			Name:        "Armada Medis Siaga 112 Jakarta",
			Type:        domain.EntityTypeVehicle,
			Status:      domain.EntityStatusMaintenance,
			Description: "Ambulans respon gawat darurat ICU keliling (sedang kalibrasi peralatan defibrillator).",
			Attributes: map[string]interface{}{
				"license_plate":       "B 9112 JKT",
				"fuel_level_pct":      88,
				"maintenance_reason":  "Defibrillator recalibration & oxygen flow check",
				"technician_assigned": "dr. Wahyu Nugroho",
			},
			Latitude:  -6.1754,
			Longitude: 106.8272,
			CreatedAt: now.Add(-24 * time.Hour),
			UpdatedAt: now.Add(-30 * time.Minute),
		},

		// ==========================================
		// 2. BANTEN (5 ENTITIES)
		// ==========================================
		{
			ID:          uuid.NewString(),
			Name:        "Terminal Feri Penyeberangan Merak",
			Type:        domain.EntityTypeFacility,
			Status:      domain.EntityStatusActive,
			Description: "Fasilitas pelabuhan penyeberangan logistik Selat Sunda penghubung Jawa dan Sumatera.",
			Attributes: map[string]interface{}{
				"dermaga_count":    7,
				"daily_traffic":    "4500 vehicles",
				"cctv_ai_gate":     true,
				"facility_manager": "Capt. Bambang Irawan",
			},
			Latitude:  -5.9320,
			Longitude: 105.9980,
			CreatedAt: now.Add(-400 * time.Hour),
			UpdatedAt: now.Add(-20 * time.Minute),
		},
		{
			ID:          uuid.NewString(),
			Name:        "Truk Tangki Kimia Cilegon Express",
			Type:        domain.EntityTypeVehicle,
			Status:      domain.EntityStatusActive,
			Description: "Angkutan tangki bahan kimia khusus bersertifikat hazmat kawasan petrokimia Cilegon.",
			Attributes: map[string]interface{}{
				"license_plate":  "A 8821 ZA",
				"fuel_level_pct": 65,
				"speed_kmh":      40,
				"hazmat_class":   "Class 3 Flammable Liquid",
				"driver_name":    "M. Ridwan",
			},
			Latitude:  -6.0167,
			Longitude: 106.0500,
			CreatedAt: now.Add(-36 * time.Hour),
			UpdatedAt: now.Add(-12 * time.Minute),
		},
		{
			ID:          uuid.NewString(),
			Name:        "Sensor Seismik Krakatau Pesisir Anyer",
			Type:        domain.EntityTypeIoTDevice,
			Status:      domain.EntityStatusActive,
			Description: "Detektor getaran seismik dan early warning tsunami Selat Sunda bekerjasama dengan BMKG.",
			Attributes: map[string]interface{}{
				"seismic_magnitude_threshold": 4.5,
				"battery_pct":                 98,
				"satellite_link":              "Iridium Active",
				"solar_charging":              true,
			},
			Latitude:  -6.0550,
			Longitude: 105.9120,
			CreatedAt: now.Add(-600 * time.Hour),
			UpdatedAt: now.Add(-4 * time.Minute),
		},
		{
			ID:          uuid.NewString(),
			Name:        "Gudang Distribusi Logistik Kargo Soetta",
			Type:        domain.EntityTypeFacility,
			Status:      domain.EntityStatusActive,
			Description: "Gudang kargo udara terpadu dan cold storage ekspor-impor Bandara Soekarno-Hatta.",
			Attributes: map[string]interface{}{
				"cold_storage_sqm": 3200,
				"dock_doors":       16,
				"temperature_c":    -18.0,
				"facility_manager": "Farhan Alamsyah",
			},
			Latitude:  -6.1275,
			Longitude: 106.6537,
			CreatedAt: now.Add(-250 * time.Hour),
			UpdatedAt: now.Add(-45 * time.Minute),
		},
		{
			ID:          uuid.NewString(),
			Name:        "Unit Rescue Derek Tol Tangerang-Merak",
			Type:        domain.EntityTypeVehicle,
			Status:      domain.EntityStatusActive,
			Description: "Kendaraan derek heavy-duty penolong insiden jalan tol koridor Banten.",
			Attributes: map[string]interface{}{
				"license_plate":  "A 9010 WL",
				"towing_cap_ton": 25,
				"fuel_level_pct": 84,
				"speed_kmh":      0,
			},
			Latitude:  -6.1850,
			Longitude: 106.4500,
			CreatedAt: now.Add(-60 * time.Hour),
			UpdatedAt: now.Add(-15 * time.Minute),
		},

		// ==========================================
		// 3. JAWA BARAT (9 ENTITIES)
		// ==========================================
		{
			ID:          uuid.NewString(),
			Name:        "Pusat Riset IoT & Telekomunikasi Bandung",
			Type:        domain.EntityTypeFacility,
			Status:      domain.EntityStatusActive,
			Description: "Laboratorium riset sensor pintar, edge computing, dan teknologi satelit telemetri nasional.",
			Attributes: map[string]interface{}{
				"lab_capacity":     120,
				"active_nodes":     450,
				"facility_manager": "Prof. Dr. Ahmad Fauzi",
				"operating_hours":  "08:00 - 20:00",
			},
			Latitude:  -6.9025,
			Longitude: 107.6186,
			CreatedAt: now.Add(-700 * time.Hour),
			UpdatedAt: now.Add(-1 * time.Hour),
		},
		{
			ID:          uuid.NewString(),
			Name:        "Sensor Vulkanik Kawah Tangkuban Parahu",
			Type:        domain.EntityTypeIoTDevice,
			Status:      domain.EntityStatusActive,
			Description: "Sensor konsentrasi gas sulfur SO2/H2S, temperatur solfatara, dan tremor seismograf kawah ratu.",
			Attributes: map[string]interface{}{
				"so2_ppm":       1.8,
				"temperature_c": 84.5,
				"status_level":  "Level I (Normal)",
				"battery_pct":   91,
			},
			Latitude:  -6.7596,
			Longitude: 107.6098,
			CreatedAt: now.Add(-800 * time.Hour),
			UpdatedAt: now.Add(-3 * time.Minute),
		},
		{
			ID:          uuid.NewString(),
			Name:        "Van Uji Lingkungan Keliling Bandung",
			Type:        domain.EntityTypeVehicle,
			Status:      domain.EntityStatusActive,
			Description: "Kendaraan uji lapangan emisi industri dan polusi air daerah aliran sungai (DAS) Citarum.",
			Attributes: map[string]interface{}{
				"license_plate":  "D 1845 BK",
				"fuel_level_pct": 74,
				"speed_kmh":      32,
				"spectrometer":   "FTIR Portable Active",
			},
			Latitude:  -6.9147,
			Longitude: 107.6098,
			CreatedAt: now.Add(-18 * time.Hour),
			UpdatedAt: now.Add(-14 * time.Minute),
		},
		{
			ID:          uuid.NewString(),
			Name:        "Stasiun Agroklimat Pintar Lembang",
			Type:        domain.EntityTypeIoTDevice,
			Status:      domain.EntityStatusActive,
			Description: "Smart farming node pengukur kelembapan tanah, radiasi surya, dan curah hujan perkebunan sayur.",
			Attributes: map[string]interface{}{
				"soil_moisture_pct": 42.8,
				"solar_rad_wm2":     620,
				"ambient_temp_c":    19.4,
				"rain_gauge_mm":     12.5,
			},
			Latitude:  -6.8120,
			Longitude: 107.6180,
			CreatedAt: now.Add(-350 * time.Hour),
			UpdatedAt: now.Add(-6 * time.Minute),
		},
		{
			ID:          uuid.NewString(),
			Name:        "Hub Manufaktur Otomotif Karawang",
			Type:        domain.EntityTypeFacility,
			Status:      domain.EntityStatusActive,
			Description: "Fasilitas perakitan komponen IoT otomotif & charging terminal armada logistik listrik.",
			Attributes: map[string]interface{}{
				"area_hectares":    12.5,
				"charging_bays":    24,
				"solar_power_kwh":  850,
				"facility_manager": "Ir. Hendro Kusumo",
			},
			Latitude:  -6.3620,
			Longitude: 107.2880,
			CreatedAt: now.Add(-500 * time.Hour),
			UpdatedAt: now.Add(-2 * time.Hour),
		},
		{
			ID:          uuid.NewString(),
			Name:        "Sensor Debit Air Waduk Saguling",
			Type:        domain.EntityTypeIoTDevice,
			Status:      domain.EntityStatusActive,
			Description: "Telemetri pemantauan elevasi air dan sedimentasi turbin PLTA Saguling DAS Citarum.",
			Attributes: map[string]interface{}{
				"water_elevation_mdpl": 642.1,
				"turbidity_ntu":        28.4,
				"generator_output_mw":  680,
				"battery_pct":          100,
			},
			Latitude:  -6.8530,
			Longitude: 107.3680,
			CreatedAt: now.Add(-900 * time.Hour),
			UpdatedAt: now.Add(-8 * time.Minute),
		},
		{
			ID:          uuid.NewString(),
			Name:        "Truk Cold-Chain Sayuran Sukabumi",
			Type:        domain.EntityTypeVehicle,
			Status:      domain.EntityStatusActive,
			Description: "Kendaraan pendingin sayuran organik dataran tinggi Sukabumi rute Jabodetabek.",
			Attributes: map[string]interface{}{
				"license_plate":  "F 8432 TF",
				"fuel_level_pct": 82,
				"box_temp_c":     4.2,
				"speed_kmh":      50,
				"driver_name":    "Asep Sunandar",
			},
			Latitude:  -6.9200,
			Longitude: 106.9250,
			CreatedAt: now.Add(-72 * time.Hour),
			UpdatedAt: now.Add(-11 * time.Minute),
		},
		{
			ID:          uuid.NewString(),
			Name:        "Depo Logistik Semen & Material Cirebon",
			Type:        domain.EntityTypeFacility,
			Status:      domain.EntityStatusActive,
			Description: "Terminal transit dan distribusi semen terpadu koridor Pantura Jawa Barat.",
			Attributes: map[string]interface{}{
				"storage_tons":     45000,
				"silo_count":       8,
				"rail_siding":      true,
				"facility_manager": "Dedi Mulyana",
			},
			Latitude:  -6.7167,
			Longitude: 108.5667,
			CreatedAt: now.Add(-420 * time.Hour),
			UpdatedAt: now.Add(-50 * time.Minute),
		},
		{
			ID:          uuid.NewString(),
			Name:        "Stasiun Cuaca Maritim Pelabuhan Cirebon",
			Type:        domain.EntityTypeIoTDevice,
			Status:      domain.EntityStatusMaintenance,
			Description: "Anemometer maritim dan sensor pasang surut air laut (perbaikan modul ultrasonik).",
			Attributes: map[string]interface{}{
				"battery_pct":         38,
				"maintenance_reason":  "Ultrasonic transducer salt-crust cleaning",
				"technician_assigned": "Ilham Saputra",
			},
			Latitude:  -6.7080,
			Longitude: 108.5780,
			CreatedAt: now.Add(-300 * time.Hour),
			UpdatedAt: now.Add(-40 * time.Minute),
		},

		// ==========================================
		// 4. JAWA TENGAH (10 ENTITIES)
		// ==========================================
		{
			ID:          uuid.NewString(),
			Name:        "Terminal Petikemas Tanjung Emas Semarang",
			Type:        domain.EntityTypeFacility,
			Status:      domain.EntityStatusActive,
			Description: "Hub logistik maritim terpadu Jawa Tengah dengan sistem dermaga cerdas.",
			Attributes: map[string]interface{}{
				"quay_cranes":      12,
				"container_yard":   "18 Hectares",
				"puddle_sensor":    "Active Auto Pump",
				"facility_manager": "Ir. Joko Susilo",
			},
			Latitude:  -6.9536,
			Longitude: 110.4208,
			CreatedAt: now.Add(-550 * time.Hour),
			UpdatedAt: now.Add(-12 * time.Minute),
		},
		{
			ID:          uuid.NewString(),
			Name:        "Armada Truk Ekspedisi Trans-Jawa 04",
			Type:        domain.EntityTypeVehicle,
			Status:      domain.EntityStatusActive,
			Description: "Truk box tronton pengantar paket ekspres rute tol Trans-Jawa Semarang - Solo - Surabaya.",
			Attributes: map[string]interface{}{
				"license_plate":  "H 8912 OA",
				"fuel_level_pct": 71,
				"speed_kmh":      68,
				"driver_name":    "Sugeng Riyadi",
				"cargo_weight":   "14.5 Tons",
			},
			Latitude:  -6.9904,
			Longitude: 110.4229,
			CreatedAt: now.Add(-28 * time.Hour),
			UpdatedAt: now.Add(-7 * time.Minute),
		},
		{
			ID:          uuid.NewString(),
			Name:        "Sensor Banjir Rob Genuk Semarang",
			Type:        domain.EntityTypeIoTDevice,
			Status:      domain.EntityStatusActive,
			Description: "Detektor elevasi rob pasang air laut dan pengontrol pompa otomatis kawasan industri Terboyo.",
			Attributes: map[string]interface{}{
				"tide_height_cm": 48,
				"pump_active":    2,
				"battery_pct":    94,
				"gsm_signal_dbm": -72,
			},
			Latitude:  -6.9620,
			Longitude: 110.4780,
			CreatedAt: now.Add(-480 * time.Hour),
			UpdatedAt: now.Add(-3 * time.Minute),
		},
		{
			ID:          uuid.NewString(),
			Name:        "Depo Kereta Api Logistik Solo Balapan",
			Type:        domain.EntityTypeFacility,
			Status:      domain.EntityStatusActive,
			Description: "Fasilitas stabling dan bongkar muat kargo rel kereta api terpadu Solo Raya.",
			Attributes: map[string]interface{}{
				"track_lanes":      6,
				"daily_trains":     14,
				"warehouse_sqm":    8000,
				"facility_manager": "Tri Wahyudi",
			},
			Latitude:  -7.5580,
			Longitude: 110.8210,
			CreatedAt: now.Add(-620 * time.Hour),
			UpdatedAt: now.Add(-2 * time.Hour),
		},
		{
			ID:          uuid.NewString(),
			Name:        "Sensor Kualitas Udara Surakarta Gladag",
			Type:        domain.EntityTypeIoTDevice,
			Status:      domain.EntityStatusActive,
			Description: "Sensor partikulat udara perkotaan dan kebisingan lalu lintas pusat kota Surakarta.",
			Attributes: map[string]interface{}{
				"pm25_ugm3":     26.1,
				"noise_db":      68.4,
				"temperature_c": 30.0,
				"humidity_pct":  72,
			},
			Latitude:  -7.5755,
			Longitude: 110.8243,
			CreatedAt: now.Add(-180 * time.Hour),
			UpdatedAt: now.Add(-9 * time.Minute),
		},
		{
			ID:          uuid.NewString(),
			Name:        "Pusat Distribusi Farmasi Magelang",
			Type:        domain.EntityTypeFacility,
			Status:      domain.EntityStatusActive,
			Description: "Gudang penyimpanan obat-obatan dingin untuk rumah sakit se-Keresidenan Kedu.",
			Attributes: map[string]interface{}{
				"vaccine_chambers": 4,
				"temperature_c":    3.8,
				"backup_genset":    "Dual Cummins 500kVA",
				"facility_manager": "apt. Dewi Kartika",
			},
			Latitude:  -7.4705,
			Longitude: 110.2178,
			CreatedAt: now.Add(-320 * time.Hour),
			UpdatedAt: now.Add(-35 * time.Minute),
		},
		{
			ID:          uuid.NewString(),
			Name:        "Kendaraan Respon Cepat BPBD Magelang",
			Type:        domain.EntityTypeVehicle,
			Status:      domain.EntityStatusActive,
			Description: "Mobil komunikasi darurat satelit dan penanggulangan bencana erupsi Merapi.",
			Attributes: map[string]interface{}{
				"license_plate":  "AA 9901 BB",
				"fuel_level_pct": 95,
				"speed_kmh":      0,
				"satellite_link": "Starlink Mobile Active",
			},
			Latitude:  -7.4900,
			Longitude: 110.2300,
			CreatedAt: now.Add(-48 * time.Hour),
			UpdatedAt: now.Add(-1 * time.Minute),
		},
		{
			ID:          uuid.NewString(),
			Name:        "Sensor Suhu Kilang Pertamina Cilacap",
			Type:        domain.EntityTypeIoTDevice,
			Status:      domain.EntityStatusActive,
			Description: "Detektor gas hidrokarbon dan sensor infra-merah suhu pipa kilang Cilacap.",
			Attributes: map[string]interface{}{
				"pipeline_temp_c":  145.2,
				"gas_leak_ppm":     0.0,
				"safety_zone":      "Zone 0 Intrinsically Safe",
				"firmware_version": "v5.0.2-sil3",
			},
			Latitude:  -7.7167,
			Longitude: 109.0167,
			CreatedAt: now.Add(-850 * time.Hour),
			UpdatedAt: now.Add(-6 * time.Minute),
		},
		{
			ID:          uuid.NewString(),
			Name:        "Truk Tangki BBM Cilacap Express",
			Type:        domain.EntityTypeVehicle,
			Status:      domain.EntityStatusActive,
			Description: "Angkutan distribusi bahan bakar solar & pertamax ke SPBU jalur selatan Jawa.",
			Attributes: map[string]interface{}{
				"license_plate":  "R 8840 PB",
				"fuel_level_pct": 89,
				"speed_kmh":      54,
				"tank_capacity":  "24,000 Liters",
				"driver_name":    "Budi Waluyo",
			},
			Latitude:  -7.6850,
			Longitude: 109.0450,
			CreatedAt: now.Add(-30 * time.Hour),
			UpdatedAt: now.Add(-18 * time.Minute),
		},
		{
			ID:          uuid.NewString(),
			Name:        "Sensor Salinitas Tambak Pekalongan",
			Type:        domain.EntityTypeIoTDevice,
			Status:      domain.EntityStatusInactive,
			Description: "Sensor salinitas dan pH air tambak udang pesisir Pekalongan (offline penggantian elektroda).",
			Attributes: map[string]interface{}{
				"battery_pct":         0,
				"maintenance_reason":  "Electrode probe replacement scheduled",
				"technician_assigned": "Slamet Santoso",
			},
			Latitude:  -6.8850,
			Longitude: 109.6750,
			CreatedAt: now.Add(-210 * time.Hour),
			UpdatedAt: now.Add(-24 * time.Hour),
		},

		// ==========================================
		// 5. D.I. YOGYAKARTA (4 ENTITIES)
		// ==========================================
		{
			ID:          uuid.NewString(),
			Name:        "Stasiun Pemantauan Gunung Merapi Babadan",
			Type:        domain.EntityTypeIoTDevice,
			Status:      domain.EntityStatusActive,
			Description: "Pos telemetri gempa vulkanik, deformasi tiltmeter, dan kamera thermal kawah puncak Merapi.",
			Attributes: map[string]interface{}{
				"tiltmeter_urad":   2.4,
				"daily_tremors":    8,
				"alert_status":     "Siaga (Level III)",
				"telemetry_uptime": "99.98%",
			},
			Latitude:  -7.5407,
			Longitude: 110.4457,
			CreatedAt: now.Add(-990 * time.Hour),
			UpdatedAt: now.Add(-2 * time.Minute),
		},
		{
			ID:          uuid.NewString(),
			Name:        "Pusat Logistik Heritage Yogyakarta",
			Type:        domain.EntityTypeFacility,
			Status:      domain.EntityStatusActive,
			Description: "Sentra kurir kerajinan lokal dan produk UMKM Yogyakarta kawasan Tugu - Malioboro.",
			Attributes: map[string]interface{}{
				"merchants_served": 450,
				"daily_dispatches": 2800,
				"solar_powered":    true,
				"facility_manager": "R. Ngesti Broto",
			},
			Latitude:  -7.7828,
			Longitude: 110.3670,
			CreatedAt: now.Add(-450 * time.Hour),
			UpdatedAt: now.Add(-40 * time.Minute),
		},
		{
			ID:          uuid.NewString(),
			Name:        "Kendaraan Listrik Shuttle Malioboro-02",
			Type:        domain.EntityTypeVehicle,
			Status:      domain.EntityStatusActive,
			Description: "Shuttle bus listrik ramah lingkungan kawasan pariwisata sumbu filosofis Yogyakarta.",
			Attributes: map[string]interface{}{
				"license_plate": "AB 1012 EV",
				"battery_pct":   81,
				"speed_kmh":     18,
				"passenger_cap": 16,
				"driver_name":   "Totok Sujarwo",
			},
			Latitude:  -7.7930,
			Longitude: 110.3655,
			CreatedAt: now.Add(-22 * time.Hour),
			UpdatedAt: now.Add(-5 * time.Minute),
		},
		{
			ID:          uuid.NewString(),
			Name:        "Sensor Elevasi Air Sungai Code Sleman",
			Type:        domain.EntityTypeIoTDevice,
			Status:      domain.EntityStatusActive,
			Description: "Detektor banjir lahar dingin dan elevasi air aliran hulu Sungai Code.",
			Attributes: map[string]interface{}{
				"water_height_cm": 120,
				"status":          "Normal",
				"battery_pct":     97,
				"rainfall_mm":     4.2,
			},
			Latitude:  -7.7600,
			Longitude: 110.3750,
			CreatedAt: now.Add(-380 * time.Hour),
			UpdatedAt: now.Add(-6 * time.Minute),
		},

		// ==========================================
		// 6. JAWA TIMUR (10 ENTITIES)
		// ==========================================
		{
			ID:          uuid.NewString(),
			Name:        "Terminal Logistik Petikemas Tanjung Perak",
			Type:        domain.EntityTypeFacility,
			Status:      domain.EntityStatusActive,
			Description: "Gerbang logistik maritim utama Indonesia Timur dengan dermaga petikemas otomatis.",
			Attributes: map[string]interface{}{
				"annual_teus":      2500000,
				"automated_cranes": 16,
				"berth_length_m":   1800,
				"facility_manager": "Ir. Edi Supriyanto",
			},
			Latitude:  -7.2023,
			Longitude: 112.7337,
			CreatedAt: now.Add(-720 * time.Hour),
			UpdatedAt: now.Add(-10 * time.Minute),
		},
		{
			ID:          uuid.NewString(),
			Name:        "Armada Truk Kontainer Perak-Gresik 08",
			Type:        domain.EntityTypeVehicle,
			Status:      domain.EntityStatusActive,
			Description: "Pengangkut kontainer baja dan semen dari kawasan industri Gresik menuju pelabuhan.",
			Attributes: map[string]interface{}{
				"license_plate":  "L 9840 UQ",
				"fuel_level_pct": 79,
				"speed_kmh":      42,
				"cargo_type":     "Export Steel Coil",
				"driver_name":    "Hariyanto",
			},
			Latitude:  -7.1850,
			Longitude: 112.6500,
			CreatedAt: now.Add(-34 * time.Hour),
			UpdatedAt: now.Add(-9 * time.Minute),
		},
		{
			ID:          uuid.NewString(),
			Name:        "Sensor Telemetri Maritim Selat Madura",
			Type:        domain.EntityTypeIoTDevice,
			Status:      domain.EntityStatusActive,
			Description: "Pengukur kecepatan arus laut, pasang surut, dan transponder kapal AIS di Jembatan Suramadu.",
			Attributes: map[string]interface{}{
				"current_speed_knots": 2.4,
				"tide_height_m":       1.6,
				"vessels_tracked":     28,
				"solar_charging":      true,
			},
			Latitude:  -7.1890,
			Longitude: 112.7750,
			CreatedAt: now.Add(-480 * time.Hour),
			UpdatedAt: now.Add(-4 * time.Minute),
		},
		{
			ID:          uuid.NewString(),
			Name:        "Pusat Sortir Paket Regional Surabaya Timur",
			Type:        domain.EntityTypeFacility,
			Status:      domain.EntityStatusActive,
			Description: "Sorting hub kurir modern berkapasitas 80.000 paket/hari kawasan Rungkut Industri.",
			Attributes: map[string]interface{}{
				"sort_capacity_hr": 8000,
				"conveyor_belts":   14,
				"facility_manager": "Dian Anggraini",
				"operating_hours":  "24/7",
			},
			Latitude:  -7.2890,
			Longitude: 112.7850,
			CreatedAt: now.Add(-310 * time.Hour),
			UpdatedAt: now.Add(-25 * time.Minute),
		},
		{
			ID:          uuid.NewString(),
			Name:        "Mobil Patroli Reaksi Cepat Surabaya",
			Type:        domain.EntityTypeVehicle,
			Status:      domain.EntityStatusActive,
			Description: "Kendaraan taktis terhubung GPS & kamera streaming langsung di jantung kota Surabaya.",
			Attributes: map[string]interface{}{
				"license_plate":  "L 1102 PB",
				"fuel_level_pct": 91,
				"speed_kmh":      28,
				"radio_channel":  "VHF Repeater Ch 4",
			},
			Latitude:  -7.2575,
			Longitude: 112.7521,
			CreatedAt: now.Add(-14 * time.Hour),
			UpdatedAt: now.Add(-3 * time.Minute),
		},
		{
			ID:          uuid.NewString(),
			Name:        "Gudang Dingin Ekspor Perikanan Sidoarjo",
			Type:        domain.EntityTypeFacility,
			Status:      domain.EntityStatusActive,
			Description: "Fasilitas blast freezer ekspor udang dan ikan bandeng berstandar HACCP.",
			Attributes: map[string]interface{}{
				"freezer_temp_c":   -24.5,
				"capacity_tons":    3500,
				"export_license":   "EU & USA Approved",
				"facility_manager": "H. Zainal Arifin",
			},
			Latitude:  -7.4520,
			Longitude: 112.7180,
			CreatedAt: now.Add(-520 * time.Hour),
			UpdatedAt: now.Add(-1 * time.Hour),
		},
		{
			ID:          uuid.NewString(),
			Name:        "Stasiun Cuaca Agrikultur Apel Batu Malang",
			Type:        domain.EntityTypeIoTDevice,
			Status:      domain.EntityStatusActive,
			Description: "IoT micro-climate monitoring kebun apel dan perkebunan hortikultura Malang Raya.",
			Attributes: map[string]interface{}{
				"temperature_c":    17.2,
				"humidity_pct":     86,
				"uv_index":         5.1,
				"frost_risk_level": "Low",
			},
			Latitude:  -7.8700,
			Longitude: 112.5250,
			CreatedAt: now.Add(-400 * time.Hour),
			UpdatedAt: now.Add(-7 * time.Minute),
		},
		{
			ID:          uuid.NewString(),
			Name:        "Truk Tangki Susu Segar Pujon-Malang",
			Type:        domain.EntityTypeVehicle,
			Status:      domain.EntityStatusActive,
			Description: "Tangki pendingin susu segar berinsulasi dari koperasi peternak sapi perah Pujon.",
			Attributes: map[string]interface{}{
				"license_plate":  "N 8214 AP",
				"fuel_level_pct": 85,
				"tank_temp_c":    3.2,
				"speed_kmh":      46,
				"volume_liters":  12000,
				"driver_name":    "Samsul Hadi",
			},
			Latitude:  -7.8500,
			Longitude: 112.4800,
			CreatedAt: now.Add(-40 * time.Hour),
			UpdatedAt: now.Add(-11 * time.Minute),
		},
		{
			ID:          uuid.NewString(),
			Name:        "Stasiun Radar Pelabuhan Ketapang Banyuwangi",
			Type:        domain.EntityTypeIoTDevice,
			Status:      domain.EntityStatusActive,
			Description: "Radar navigasi dan telemetri pemantau kepadatan kapal penyeberangan Selat Bali.",
			Attributes: map[string]interface{}{
				"radar_range_nm": 18,
				"ais_target_cnt": 34,
				"battery_pct":    99,
				"solar_charging": true,
			},
			Latitude:  -8.1400,
			Longitude: 114.4000,
			CreatedAt: now.Add(-750 * time.Hour),
			UpdatedAt: now.Add(-5 * time.Minute),
		},
		{
			ID:          uuid.NewString(),
			Name:        "Depo Logistik Industri Kereta Madiun (INKA)",
			Type:        domain.EntityTypeFacility,
			Status:      domain.EntityStatusActive,
			Description: "Hub penyimpanan komponen manufaktur perkeretaapian dan perakitan gerbong kereta.",
			Attributes: map[string]interface{}{
				"yard_sqm":         32000,
				"steel_stock_tons": 8400,
				"facility_manager": "Ir. Sigit Purnomo",
				"operating_hours":  "07:00 - 22:00",
			},
			Latitude:  -7.6250,
			Longitude: 111.5250,
			CreatedAt: now.Add(-610 * time.Hour),
			UpdatedAt: now.Add(-30 * time.Minute),
		},
	}
}

// SeedInitialDataIfEmpty seeds sample realistic Java geospatial entities if the database is empty.
func (r *sqliteEntityRepository) SeedInitialDataIfEmpty(ctx context.Context) error {
	var count int
	err := r.db.QueryRowContext(ctx, "SELECT COUNT(*) FROM entities").Scan(&count)
	if err != nil {
		return err
	}
	if count > 0 {
		return nil
	}

	return r.insertSeedEntities(ctx)
}

// ResetAndSeed clears all existing entities and seeds full Java geospatial entities.
func (r *sqliteEntityRepository) ResetAndSeed(ctx context.Context) error {
	if _, err := r.db.ExecContext(ctx, "DELETE FROM entities"); err != nil {
		return err
	}
	return r.insertSeedEntities(ctx)
}

func (r *sqliteEntityRepository) insertSeedEntities(ctx context.Context) error {
	samples := getJavaSeedEntities()
	for _, s := range samples {
		if err := r.Create(ctx, s); err != nil {
			return err
		}
	}
	return nil
}
